# TCEQ data parser and object creation

file_dir = 'C:/vwts/TCEQ/code'

# TCEQ objects contain table_name keys with dictionary objects.
# each table_name key has a dictionary keyed on a column_name with a tuple value
# The tuple represents the character space delimiter for that field ex: "column_01" : (1,4)
tceq_objects_nor_txt = {
    "billing_contact" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5),
        "ac_cont_last_name_txt" : (6 , 55),
        "ac_cont_first_name_txt" : (56 , 85),
        "ac_day_actv_cont_job_title" : (86 , 110),
        "ad_electr_commu_phone" : (111 , 140),
        "ad_address_deliv_txt" : (141 , 183),
        "ad_address_deliv_2_txt" : (184 , 223),
        "ad_address_city_name" : (224 , 259),
        "ad_address_usps_state_cd" : (260 , 261),
        "ad_address_zip_cd" : (262 , 266),
        "ad_address_zip_plus4_cd" : (267 , 270),
        "bt_ars_ar_num" : (271 , 280),
        "ac_cont_last_name_txt_att" : (281 , 360),
        "ac_cont_first_name_txt_att" : (361 , 400),
        "bt_ar_intfs_ar_suffix_txt" : (401 , 403),
    },
    "contact" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5),
        "ac_cont_last_name_txt" : (6 , 55),
        "ac_cont_first_name_txt" : (56 , 85),
        "ac_day_actv_cont_job_title" : (86 , 110),
        "ac_day_actv_cont_role_cd" : (111 , 140),
        "ad_address_deliv_txt" : (141 , 182),
        "ac_dac_addr_int_txt" : (183 , 222),
        "ad_address_deliv_txt" : (223 , 248),
        "ad_address_city_name" : (249 , 284),
        "ad_address_usps_state_cd" : (285 , 286),
        "ad_address_zip_cd" : (287 , 291),
        "ad_address_zip_plus4_cd" : (292 , 295),
        "ad_electr_commu_phone" : (296 , 325),
        "ad_electr_commu_fax" : (326 , 355),
        "ad_electr_commu_email_addr_txt" : (356 , 395),
    },
    "eparef" : {
        "pa_ref_gen_cd_gen_cd_txt" : (1 , 4),
        "line_sequence" : (5 , 7),
        "pa_ref_gen_cd_desc_txt" : (8 , 87),
    },
    "epawst" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5),
        "pa_ihw_twc_ehwn_twc_id" : (6 , 13),
        "pa_ihw_twc_ehwn_ehwn_cd" : (14 , 17),
    },
    "fac" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5    ),
        "lm_addn_id_alt_reg_ent_name" : (6 , 55   ),
        "pa_ihw_fac_nor_create_dt" : (56 , 63  ),
        "pa_ihw_fac_sign_dt" : (64 , 71  ),
        "lm_addn_id_add_num_txt" : (72 , 83  ),
        "pa_ihw_fac_hw_pmt_num_txt" : (84 , 88  ),
        "re_geo_loc_phys_loc_desc_txt" : (89 , 148 ),
        "lm_addn_id_indus_typ" : (149 , 153),
        "lm_addn_id_site_class_generator" : (154 , 154),
        "lm_addn_id_site_class_receiver" : (155 , 155),
        "lm_addn_id_site_class_transporter" : (156 , 156),
        "lm_addn_id_site_class_facility" : (157 , 157),
        "pa_ihw_maq_interrogation" : (158 , 158),
        "pa_ihw_fac_regis_status_cd" : (159 , 183),
        "lm_addn_id_site_class" : (184 , 203),
        "pa_ihw_fac_genr_typ_cd" : (204 , 238),
        "lj_county_cnty_fips_cd" : (239 , 241),
        "lj_tnrcc_region_tnrcc_region_cd" : (242 , 243),
        "ad_address_deliv_txt" : (244 , 325),
        "ad_address_city_name" : (326 , 361),
        "re_geo_loc_loc_cnty_name" : (362 , 376),
        "lj_country_cntry_name" : (377 , 389),
        "ad_address_usps_state_cd" : (390 , 391),
        "ad_address_zip_cd" : (392 , 396),
        "pr_principal_princ_name"  : (397 , 446),
        "ad_address_deliv_txt" : (447 , 514),
        "ac_dac_addr_int_txt" : (515 , 554),
        "ad_address_city_name" : (555 , 590),
        "lj_country_cntry_name" : (591 , 603),
        "ad_address_usps_state_cd" : (604 , 605),
        "ad_address_zip_cd"  : (606 , 610),
        "ad_address_zip_plus4_cd" : (611 , 614),
        "ac_cont_last_name_txt" : (615 , 664),
        "ac_cont_first_name_txt" : (665 , 694),
        "ad_electr_commu_area_cd" : (695 , 724),
        "pa_ihw_fac_ihw_fac_id" : (725 , 730),
        "pr_principal_fed_tax_id_num" : (731 , 741),
        "re_geo_loc_lat_dec_coord_num" : (742 , 748),
        "re_geo_loc_long_dec_coord_num" : (749 , 756),
        "pa_ihw_fac_last_nor_upd_dt" : (757 , 764),
        "pa_ihw_fac_iw_pmt_num_txt" : (765 , 769),
        "pa_ihw_fac_mw_pmt_num_txt" : (770 , 774),
        "lm_addn_id_site_class" : (775 , 775),
        "pa_ihw_fac_steers_flg" : (776 , 776),
        "pa_ihw_fac_aws_reqd_flg" : (777 , 777),
        "lm_addn_id_site_class" : (778 , 778),
        "rf_indus_typ_indus_typ_cd" : (779 , 784),
        "pa_hist_create_tmstmp" : (785 , 792),
        "pa_ihw_fac_mwrs_reqd_flg" : (793 , 793),
        "pa_ihw_fac_land_typ_cd"  : (794 , 803),
        "pa_ihw_fac_rcvr_fac_cat_cd" : (804 , 813),
        "pa_ihw_fac_trans_bus_status_cd" : (814 , 814),
        "pa_ihw_fac_trans_bus_status_cd" : (815 , 815),
        "pa_ihw_wst_class_manage_wst_class_cd_1" : (816 , 817),
        "pa_ihw_wst_class_manage_wst_class_cd_2" : (818 , 819),
        "pa_ihw_wst_class_manage_wst_class_cd_3" : (820 , 821),
        "pa_ihw_wst_class_manage_wst_class_cd_H" : (822 , 823),
        "blank_msw" : (824 , 825),
        "blank_medical" : (826 , 827),
        "blank_other" : (828 , 829),
        "blank_sludge" : (830 , 831),
        "blank_used_oil" : (832 , 833),
        "blank_used_tires" : (834 , 835),
        "pa_ihw_fac_survivor_ihw_fac_id" : (836 , 841),
        "lm_addn_id_addn_id_status_cd" : (842 , 851),
    },
    "genref" : {
        "pa_ref_gen_cd_typ_ref_name_txt" : (1 , 50),
        "an_integer_value" : (51 , 58),
        "pa_ref_gen_cd_gen_cd_txt" : (59 , 68),
        "pa_ref_gen_cd_name_txt" : (69 , 93),
        "pa_ref_gen_cd_desc_txt" : (94 , 143),
    },
    "oper" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5),
        "pr_principle_last_name" : (6 , 55),
        "pr_principle_first_name" : (56 , 85),
        "ad_address_deliv_txt" : (86 , 127),
        "ac_dac_addr_int_txt" : (128 , 167),
        "ad_address_deliv_txt" : (168 , 193),
        "ad_address_city_name" : (194 , 229),
        "ad_address_usps_state_cd" : (230 , 231),
        "ad_address_zip_cd" : (232 , 236),
        "ad_address_zip_plus4_cd" : (237 , 240),
        "lj_country_cntry_name" : (241 , 250),
        "ad_electr_commu_phone" : (251 , 280),
        "ad_electr_commu_fax" : (281 , 310),
        "ad_electr_commu_email_addr_txt" : (311 , 350 ),
        "rf_gen_cd_name_txt" : (351 , 380),
        "pr_principle_fed_tax_id_num" : (381 , 391),
        "py_adm_active" : (392 , 392),
    },
    "ots" : {
        "pa_ihw_ots_req_ihw_fac_id" : (1 , 6),
        "v_pa_norextract_swr_num_txt" : (7 , 11),
        "pa_ihw_ots_req_ots_req_id" : (12 , 16),
        "lm_addn_id_add_num_txt" : (17 , 28),
        "lm_addn_id_alt_reg_ent_name" : (29 , 78),
        "re_geo_loc_phys_loc_desc_txt" : (79 , 138),
        "ad_address_deliv_txt" : (139 , 218),
        "ad_address_city_name" : (219 , 248),
        "ad_address_zip_cd" : (249 , 253),
        "pa_gen_ref_name_txt" : (254 , 263),
        "lj_county_cnty_fips_cd" : (264 , 266),
        "re_geo_loc_loc_cnty_name" : (267 , 281),
        "lj_tnrcc_region_tnrcc_region_cd" : (282 , 283),
        "pa_ihw_ots_req_req_rcv_dt" : (284 , 291),
        "pr_principal_last_name" : (292 , 337),
        "ac_cont_org_name_txt" : (338 , 387),
        "ad_address_deliv_txt"  : (388 , 467),
        "ad_address_city_name" : (468 , 497),
        "ad_address_usps_state_cd" : (498 , 499),
        "ad_address_zip_cd" : (500 , 504),
        "ad_address_zip_plus4_cd" : (505 , 508),
        "ad_address_cntry_cd" : (509 , 511),
        "own_oper_phone" : (512 , 533),
        "own_oper_fax" : (534 , 555),
        "lm_addn_id_indus_indus_typ_cd" : (556 , 561),
        "ac_day_actv_cont_org_name_txt" : (562 , 611),
        "ad_address_deliv_txt" : (612 , 691),
        "ad_address_city_name" : (692 , 721),
        "ad_address_usps_state_cd" : (722 , 723),
        "ad_address_zip_cd" : (724 , 728),
        "ad_address_zip_plus4_cd" : (729 , 732),
        "ad_address_cntry_cd" : (733 , 735),
        "broker_phone" : (736 , 757),
        "broker_fax" : (758 , 779),
        "pa_ihw_wst_stream_ots_prc_cmp_dt" : (780 , 787),
        "pa_ihw_wst_stream_tx_wst_cd" : (788 , 795),
        "pa_ihw_wst_stream_wst_desc_txt" : (796 , 875),
        "pa_ihw_wst_stream_tx_form_cd" : (876 , 878),
        "pa_ihw_wst_stream_wst_class_cd" : (879),
        "pa_ihw_wst_stream_origin_cd" : (880),
        "pa_ihw_wst_stream_wst_source_cd" : (881 , 883),
        "pa_ihw_wst_stream_sys_typ_cd" : (884 , 886),
        "pa_ihw_wst_stream_epa_form_cd" : (887 , 889),
        "pa_ihw_wst_stream_naics_cd" : (890 , 895),
        "pa_ihw_wst_stream_twc_id" : (896 , 903),
    },
    "ots_ehwn" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5),
        "pa_ihw_ots_req_ots_req_id" : (6 , 10),
        "pa_ihw_wst_stream_twc_id" : (11 , 18),
        "pa_ihw_wst_stream_tx_wst_cd" : (19 , 26),
        "pa_ihw_twc_ehwn_ehwn_cd" : (27 , 30),
    },
    "own" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5),
        "pr_principle_last_name" : (6 , 55),
        "pr_principle_first_name" : (56 , 85),
        "ad_address_deliv_txt" : (86 ,  127),
        "ac_dac_addr_int_txt" : (128 , 167),
        "ad_address_deliv_txt" : (168 , 193),
        "ad_address_city_name" : (194 , 229),
        "ad_address_usps_state_cd" : (230 , 231),
        "ad_address_zip_cd" : (232 , 236),
        "ad_address_zip_plus4_cd": (237 , 240),
        "lj_country_cntry_name" : (241 , 250),
        "ad_electr_commu_phone": (251 , 280),
        "ad_electr_commu_fax" : (281 , 310),
        "ad_electr_commu_email_addr_txt" : (311 , 350 ),
        "rf_gen_cd_name_txt": (351 , 380),
        "pr_principle_fed_tax_id_num": (381 , 391),
        "py_adm_active" : (392 , 392),
    },
    "unit" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5),
        "pa_ihw_wmu_wmu_seq_num" : (6 , 8),
        "pa_ihw_wmu_wmu_typ_cd" : (9 , 10),
        "pa_ihw_wmu_wmu_regis_status_cd" : (11 , 25),
        "pa_ihw_wmu_wmu_reg_status_cd" : (26 , 65),
        "pa_ihw_wmu_uic_pmt_num_txt" : (66 , 70),
        "pa_ihw_wmu_wmu_cap_qty" : (71 , 81),
        "pa_ihw_wmu_wmu_cap_units_cd" : (82 , 82),
        "pa_ihw_wmu_off_wst_class_wst_class_cd_H" : (83 , 83),
        "pa_ihw_wmu_off_wst_class_wst_class_cd_1" : (84 , 84),
        "pa_ihw_wmu_off_wst_class_wst_class_cd_2" : (85 , 85),
        "pa_ihw_wmu_off_wst_class_wst_class_cd_3" : (86 , 86),
        "pa_ihw_wmu_off_wst_class_wst_class_cd_N" : (87 , 87),
        "pa_ihw_wmu_wmu_pmt_num_txt" : (88 , 90),
        "pa_ihw_wmu_wmu_desc_txt" : (91 , 690),
        "pa_ihw_wmu_wmu_regis_status_dt" : (691 , 698),
        "pa_ihw_wmu_stc_sys_typ_cd_H" : (699 , 701),
        "pa_ihw_wmu_stc_sys_typ_cd_1" : (702 , 704),
        "pa_ihw_wmu_stc_sys_typ_cd_2" : (705 , 707),
        "pa_ihw_wmu_stc_sys_typ_cd_3" : (708 , 710),
        "pa_ihw_wmu_stc_sys_typ_cd_N" : (711 , 713),
        "deed_record_needed" : (714 , 714),
        "pa_ihw_wmu_deed_rcrd_dt" : (715 , 722),
    },
    "unit_desc" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5),
        "pa_ihw_fac_ihw_fac_id" : (6 , 11),
        "pa_ihw_wmu_wmu_seq_num_txt" : (12 , 14),
        "pa_ihw_wmu_wmu_desc_txt" : (15 , 334),
    },
    "unitwst" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5),
        "pa_ihw_wmu_wmu_seq_num_txt" : (6 , 8),
        "pa_ihw_wmu_twc_xref_twc_id" : (9 , 16),
        "pa_ihw_wmu_twc_xref_curr_prev_cd" : (17 , 17),
    },
    "wst_desc" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5),
        "pa_ihw_fac_ihw_fac_id" : (6 , 11),
        "pa_ihw_wst_stream_twc_id" : (12 , 19),
        "texas_waste_code" : (20 , 25),
        "pa_ihw_wst_stream_tx_wst_cd" : (26 , 33),
        "pa_ihw_wst_stream_wst_desc_txt" : (34 , 113),
    },
    "nor_ext_universal" : {
        "pa_ihw_fac_swr_num_txt" : (1 , 5),
        "pa_ihw_fac_univ_wst_lrg_qty_hand_flg" : (6 , 6),
        "pa_ihw_univ_wst_univ_wst_cd_b" : (7 , 7),
        "pa_ihw_univ_wst_univ_wst_cd_p" : (8 , 8),
        "pa_ihw_univ_wst_univ_wst_cd_t" : (9 , 9),
        "pa_ihw_univ_wst_univ_wst_cd_l" : (10 , 10),
        "pa_ihw_univ_wst_univ_wst_cd_r" : (11 , 11),
        "pa_ihw_fac_univ_wst_dest_fac_flg" : (12 , 12),
    },
}

tceq_objects_summary_csv = {
    "Annual_Waste_Summary" : {
        "summary_code_annual_waste" : (1 , 2),
        "pa_ihw_fac_swr_num_txt" : (3 , 7),
        "pa_ihw_aws_hdr_rpt_yr" : (8 , 11),
        "pa_ihw_aws_twc_twc_cd" : (12 , 19),
        "classification_of_waste_code" : (20 , 20),
        "waste_form_code" : (21 , 23),
        "pa_ihw_aws_twc_total_wst_gen_qty" : (24 , 37),
        "pa_ihw_aws_twc_total_wst_gen_units_cd" : (38 , 38),
        "pa_ihw_aws_dtl_wst_hndl_qty" : (39 , 52),
        "pa_ihw_aws_dtl_wst_hndl_units_cd" : (53 , 53),
        "pa_ihw_aws_dtl_sys_typ_cd" : (54 , 56),
        "pa_ihw_aws_dtl_rcvr_swr_num_txt" : (57 , 61),
        "pa_ihw_aws_dtl_rcvr_epa_id_txt" : (62 , 73),
        "pa_ihw_aws_dtl_comnt_txt" : (74 , 108),
        "pa_ihw_aws_dtl_fee_exempt_req_cd" : (109 , 109),
        "pa_ihw_aws_dtl_fee_exempt_resol_cd" : (110 , 110),
        "report_was_required" : (111 , 111),
        "pa_ihw_aws_dtl_create_tmstmp" : (112 , 119),
        "pa_ihw_aws_dtl_err_flg" : (120 , 120),
        "pa_ihw_aws_dtl_rpt_meth_cd" : (121 , 121),
        "pa_ihw_aws_dtl_aws_dtl_id" : (122 , 129),
        "pa_ihw_aws_ehwn_ehwn_cd_H" : (130 , 133),
        "pa_ihw_aws_ehwn_ehwn_cd_1" : (134 , 137),
        "pa_ihw_aws_ehwn_ehwn_cd_2" : (138 , 141),
        "pa_ihw_aws_ehwn_ehwn_cd_3" : (142 , 145),
        "pa_ihw_aws_dtl_subm_co_name" : (146 , 195),
        "pa_ihw_aws_dtl_auth_agent_name" : (196 , 225),
        "pa_ihw_aws_dtl_auth_agent_title" : (226 , 255),
        "pa_ihw_aws_hdr_hw_greater_1_1_tons_flg" : (256 , 256),
        "pa_ihw_aws_hdr_acute_hw_greater_2_2_lbs_flg" : (257 , 257),
    },
    "Waste_Shipment_Summary" : {
        "summary_code_waste_shipments" : (1 , 2),
        "pa_ihw_ots_req_ots_req__id" : (3 , 7),
        "pr_principal_princ_name" : (8 , 57 ),
        "pa_ihw_ots_wss_manifest_num_txt" : (58 , 69 ),
        "pa_ihw_ots_wss_rcvr_swr_num_txt" : (70 , 74 ),
        "pa_ihw_ots_wss_rcvr_epa_id_txt" : (75 , 86 ),
        "pa_ihw_ots_wss_twc_cd" : (87 , 94 ),
        "pa_ihw_wst_stream_wst_class_cd" : (95 , 95 ),
        "pa_ihw_wst_stream_tx_form_cd" : (96 , 98 ),
        "pa_ihw_ots_wss_wss_qty" : (99 , 112 ),
        "pa_ihw_ots_wss_wss_qty_units_cd" : (113 , 113 ),
        "pa_ihw_ots_wss_sys_typ_cd" : (114 , 116 ),
        "pa_ihw_ots_wss_ship_dt" : (117 , 124 ),
        "pa_ihw_ots_wss_trans_swr_num_txt" : (125 , 129 ),
        "pa_ihw_ots_wss_subm_co_name" : (130 , 179 ),
        "pa_ihw_ots_wss_auth_agent_name"  : (180 , 209),
        "pa_ihw_ots_wss_auth_agent_title" : (210 , 239),
        "pa_ihw_ots_wss_create_tmstmp" : (240 , 247 ),
        "pa_ihw_ots_wss_err_flg" : (248 , 248 ),
        "pa_ihw_ots_wss_ots_wss_id" : (249 , 256 ),
        "pa_ihw_wst_stream_twc_id" : (257 , 264  ),
    },
    "Monthly_Waste_Receipt_Summary" : {
        "summary_code_monthly_waste_receipts" : (1 , 2),
        "pa_ihw_fac_swr_num_txt"  : (3 , 7),
        "pa_ihw_mwrs_dtl_manifest_num_txt" : (8 , 19),
        "pa_ihw_mwrs_dtl_genr_swr_num_txt" : (20 , 24),
        "pa_ihw_mwrs_dtl_genr_epa_id_txt" : (25 , 36),
        "pa_ihw_mwrs_dtl_twc_cd" : (37 , 44),
        "waste_classification" : (45 , 45),
        "waste_form_code" : (46 , 48),
        "pa_ihw_mwrs_dtl_mwrs_qty" : (49 , 62),
        "pa_ihw_mwrs_dtl_mwrs_qty_units_cd" : (63 , 63),
        "pa_ihw_mwrs_dtl_sys_typ_cd" : (64 , 66),
        "pa_ihw_mwrs_dtl_rcv_dt" : (67 , 74),
        "pa_ihw_mwrs_dtl_trans_swr_num_txt" : (75 , 79),
        "comment" : (80 , 114),
        "lm_addn_id_alt_reg_ent_name" : (115 , 164),
        "pa_ihw_mwrs_dtl_rpt_meth_cd" : (165 , 165),
        "pa_ihw_mwrs_hdr_shipment_rcv_flg" : (166 , 166),
        "pa_ihw_mwrs_dtl_create_tmstmp" : (167 , 174),
        "pa_ihw_mwrs_hdr_rpt_month_yr" : (175 , 180),
        "pa_ihw_mwrs_dtl_err_flg" : (181 , 181),
        "pa_ihw_mwrs_dtl_mwrs_dtl_id" : (182 , 189),
        "pa_ihw_mwrs_ehwn_ehwn_cd" : (190 , 193),
        "pa_ihw_mwrs_ehwn_ehwn_cd" : (194 , 197),
        "pa_ihw_mwrs_ehwn_ehwn_cd" : (198 , 201),
        "pa_ihw_mwrs_ehwn_ehwn_cd" : (202 , 205),
        "pa_ihw_mwrs_dtl_subm_co_name" : (206 , 255),
        "pa_ihw_mwrs_dtl_auth_agent_name" : (256 , 285),
        "pa_ihw_mwrs_dtl_auth_agent_title" : (286 , 315),
    },
}



